#include "assets/misc/wolf_animetion/AllAnim.h"

// ========================
// === Temporary Animations

#define TEMP_WOLF_ANIM(frameCount) gLinkWolfTempAnim_##frameCount
#define CREATE_TEMP_WOLF_ANIM(frameCount) extern LinkAnimationHeader TEMP_WOLF_ANIM(frameCount)
CREATE_TEMP_WOLF_ANIM(3);
CREATE_TEMP_WOLF_ANIM(4);
CREATE_TEMP_WOLF_ANIM(5);
CREATE_TEMP_WOLF_ANIM(6);
CREATE_TEMP_WOLF_ANIM(7);
CREATE_TEMP_WOLF_ANIM(8);
CREATE_TEMP_WOLF_ANIM(9);
CREATE_TEMP_WOLF_ANIM(10);
CREATE_TEMP_WOLF_ANIM(11);
CREATE_TEMP_WOLF_ANIM(12);
CREATE_TEMP_WOLF_ANIM(13);
CREATE_TEMP_WOLF_ANIM(14);
CREATE_TEMP_WOLF_ANIM(15);
CREATE_TEMP_WOLF_ANIM(16);
CREATE_TEMP_WOLF_ANIM(17);
CREATE_TEMP_WOLF_ANIM(18);
CREATE_TEMP_WOLF_ANIM(19);
CREATE_TEMP_WOLF_ANIM(20);
CREATE_TEMP_WOLF_ANIM(21);
CREATE_TEMP_WOLF_ANIM(22);
CREATE_TEMP_WOLF_ANIM(23);
CREATE_TEMP_WOLF_ANIM(24);
CREATE_TEMP_WOLF_ANIM(25);
CREATE_TEMP_WOLF_ANIM(26);
CREATE_TEMP_WOLF_ANIM(27);
CREATE_TEMP_WOLF_ANIM(28);
CREATE_TEMP_WOLF_ANIM(29);
CREATE_TEMP_WOLF_ANIM(30);
CREATE_TEMP_WOLF_ANIM(31);
CREATE_TEMP_WOLF_ANIM(32);
CREATE_TEMP_WOLF_ANIM(33);
CREATE_TEMP_WOLF_ANIM(34);
CREATE_TEMP_WOLF_ANIM(35);
CREATE_TEMP_WOLF_ANIM(36);
CREATE_TEMP_WOLF_ANIM(37);
CREATE_TEMP_WOLF_ANIM(38);
CREATE_TEMP_WOLF_ANIM(39);
CREATE_TEMP_WOLF_ANIM(40);
CREATE_TEMP_WOLF_ANIM(41);
CREATE_TEMP_WOLF_ANIM(42);
CREATE_TEMP_WOLF_ANIM(43);
CREATE_TEMP_WOLF_ANIM(44);
CREATE_TEMP_WOLF_ANIM(45);
CREATE_TEMP_WOLF_ANIM(46);
CREATE_TEMP_WOLF_ANIM(47);
CREATE_TEMP_WOLF_ANIM(48);
CREATE_TEMP_WOLF_ANIM(49);
CREATE_TEMP_WOLF_ANIM(50);
CREATE_TEMP_WOLF_ANIM(51);
CREATE_TEMP_WOLF_ANIM(52);
CREATE_TEMP_WOLF_ANIM(53);
CREATE_TEMP_WOLF_ANIM(54);
CREATE_TEMP_WOLF_ANIM(55);
CREATE_TEMP_WOLF_ANIM(56);
CREATE_TEMP_WOLF_ANIM(57);
CREATE_TEMP_WOLF_ANIM(58);
CREATE_TEMP_WOLF_ANIM(59);
CREATE_TEMP_WOLF_ANIM(60);
CREATE_TEMP_WOLF_ANIM(61);
CREATE_TEMP_WOLF_ANIM(62);
CREATE_TEMP_WOLF_ANIM(63);
CREATE_TEMP_WOLF_ANIM(64);
CREATE_TEMP_WOLF_ANIM(65);
CREATE_TEMP_WOLF_ANIM(66);
CREATE_TEMP_WOLF_ANIM(67);
CREATE_TEMP_WOLF_ANIM(68);
CREATE_TEMP_WOLF_ANIM(69);
CREATE_TEMP_WOLF_ANIM(70);
CREATE_TEMP_WOLF_ANIM(71);
CREATE_TEMP_WOLF_ANIM(72);
CREATE_TEMP_WOLF_ANIM(73);
CREATE_TEMP_WOLF_ANIM(74);
CREATE_TEMP_WOLF_ANIM(75);
CREATE_TEMP_WOLF_ANIM(76);
CREATE_TEMP_WOLF_ANIM(77);
CREATE_TEMP_WOLF_ANIM(78);
CREATE_TEMP_WOLF_ANIM(79);
CREATE_TEMP_WOLF_ANIM(80);
CREATE_TEMP_WOLF_ANIM(81);
CREATE_TEMP_WOLF_ANIM(82);
CREATE_TEMP_WOLF_ANIM(83);
CREATE_TEMP_WOLF_ANIM(84);
CREATE_TEMP_WOLF_ANIM(85);
CREATE_TEMP_WOLF_ANIM(86);
CREATE_TEMP_WOLF_ANIM(87);
CREATE_TEMP_WOLF_ANIM(88);
CREATE_TEMP_WOLF_ANIM(89);
CREATE_TEMP_WOLF_ANIM(113);
CREATE_TEMP_WOLF_ANIM(120);
CREATE_TEMP_WOLF_ANIM(131);
CREATE_TEMP_WOLF_ANIM(178);
CREATE_TEMP_WOLF_ANIM(195);
CREATE_TEMP_WOLF_ANIM(208);
CREATE_TEMP_WOLF_ANIM(230);
CREATE_TEMP_WOLF_ANIM(252);
#undef CREATE_TEMP_WOLF_ANIM

// Helpers to get the temp animation w/ a specific number of frames.
#define GET_TEMP_WOLF_ANIM(adult, frameCount) LINK_AGE_VALUE(&(adult), &TEMP_WOLF_ANIM(frameCount))

// === Temporary Animations
// ========================
